import warnings


warnings.filterwarnings(
    "ignore",
    message="'audioop' is deprecated and slated for removal in Python 3.13",
    category=DeprecationWarning,
)
warnings.filterwarnings(
    "ignore",
    message="'aifc' is deprecated and slated for removal in Python 3.13",
    category=DeprecationWarning,
)
warnings.filterwarnings(
    "ignore",
    message="Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work",
    category=RuntimeWarning,
)
warnings.filterwarnings(
    "ignore",
    message="Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work",
    category=RuntimeWarning,
)

from .app_mixins import (
    ChatUiMixin,
    ClipboardMixin,
    DiagnosticsToolsMixin,
    ScrollingMixin,
    SettingsUiMixin,
    UpdateFlowMixin,
    VoicePipelineMixin,
)
from .audio_devices import (
    expand_audio_device_name as _expand_audio_device_name,
    find_audio_device_entry_by_name as _find_audio_device_entry_by_name,
    get_audio_device_entry as _get_audio_device_entry,
    is_audio_garbage_name as _is_audio_garbage_name,
    list_input_device_entries_safe,
    list_microphone_names_safe,
    list_output_device_entries_safe,
    list_output_device_names_safe,
    pick_microphone_device,
    pick_output_device,
)
from .branding import (
    APP_DIR_NAME,
    APP_EXECUTABLE_BASENAME,
    APP_EXECUTABLE_NAME,
    APP_INSTALLER_NAME,
    APP_LOGGER_NAME,
    APP_NAME,
    APP_RELEASE_BUNDLE_PREFIX,
    APP_USER_AGENT,
    APP_VERSION,
    APP_WINDOWS_APP_ID,
    app_brand_name,
    app_dialog_title,
    app_title,
    app_version_badge,
)
from .commands import (
    CommandParser,
    SIMPLE_BATCH_ACTIONS,
    SPLIT_PATTERN,
    detect_wake_word,
    find_dynamic_entry,
    find_app_key,
    get_dynamic_entries,
    get_dynamic_entry_by_key,
    make_dynamic_key,
    normalize_text,
    strip_wake_word,
)
from .controllers import ActionExecutor, AppControllers, ConversationController, UiShell, VoiceController, WindowController, build_app_controllers
from .custom_actions import custom_actions_example, load_custom_action_entries
from .diagnostics import DiagnosticAssistant
from .effects import DvdLogoBouncer
from .reminders import ReminderScheduler
from .release_meta import DEFAULT_GITHUB_REPO, DEFAULT_RELEASES_URL, DEFAULT_RELEASE_API_URL
from .runtime import parse_geometry, resource_path, runtime_root_path, set_windows_app_id
from .service_hub import ServiceHub, build_service_hub
from .setup_wizard import SetupWizard
from .state import (
    CONFIG,
    CONFIG_MGR,
    PROMPT_MGR,
    LOCAL_APPDATA,
    ROAMING_APPDATA,
    USER_PROFILE,
    db,
    get_config_path,
    get_db_path,
    get_prompts_dir,
)
from .storage import (
    app_config_dir,
    app_data_dir,
    app_log_dir,
    config_path,
    custom_actions_path,
    db_path,
    fix_history_path,
    prompts_dir,
    update_status_path,
)
from .telegram_bot import TelegramBot
from .theme import Theme
from .update_helpers import (
    extract_sha256,
    format_release_notes_for_chat,
    is_installer_asset_name,
    is_newer_version,
    is_trusted_update_url,
    normalize_trusted_hosts,
    pick_release_asset,
    version_tuple,
)
from .voice_profiles import LISTENING_PROFILES, apply_device_listening_tuning, get_capture_timing, profile_values

__all__ = [
    "APP_DIR_NAME",
    "APP_EXECUTABLE_BASENAME",
    "APP_EXECUTABLE_NAME",
    "APP_INSTALLER_NAME",
    "APP_LOGGER_NAME",
    "APP_NAME",
    "APP_RELEASE_BUNDLE_PREFIX",
    "APP_USER_AGENT",
    "APP_VERSION",
    "APP_WINDOWS_APP_ID",
    "ChatUiMixin",
    "ClipboardMixin",
    "CommandParser",
    "CONFIG",
    "CONFIG_MGR",
    "ActionExecutor",
    "AppControllers",
    "ConversationController",
    "DEFAULT_GITHUB_REPO",
    "DEFAULT_RELEASES_URL",
    "DEFAULT_RELEASE_API_URL",
    "DiagnosticAssistant",
    "DiagnosticsToolsMixin",
    "DvdLogoBouncer",
    "LOCAL_APPDATA",
    "PROMPT_MGR",
    "ROAMING_APPDATA",
    "ReminderScheduler",
    "SIMPLE_BATCH_ACTIONS",
    "SPLIT_PATTERN",
    "ScrollingMixin",
    "ServiceHub",
    "SettingsUiMixin",
    "SetupWizard",
    "TelegramBot",
    "Theme",
    "UiShell",
    "USER_PROFILE",
    "UpdateFlowMixin",
    "VoicePipelineMixin",
    "VoiceController",
    "WindowController",
    "LISTENING_PROFILES",
    "_expand_audio_device_name",
    "_find_audio_device_entry_by_name",
    "_get_audio_device_entry",
    "_is_audio_garbage_name",
    "apply_device_listening_tuning",
    "app_brand_name",
    "app_config_dir",
    "app_data_dir",
    "app_dialog_title",
    "app_log_dir",
    "app_title",
    "app_version_badge",
    "build_service_hub",
    "build_app_controllers",
    "config_path",
    "custom_actions_example",
    "custom_actions_path",
    "db",
    "db_path",
    "extract_sha256",
    "fix_history_path",
    "format_release_notes_for_chat",
    "find_app_key",
    "find_dynamic_entry",
    "get_dynamic_entries",
    "get_dynamic_entry_by_key",
    "get_capture_timing",
    "make_dynamic_key",
    "is_installer_asset_name",
    "is_newer_version",
    "is_trusted_update_url",
    "normalize_text",
    "normalize_trusted_hosts",
    "parse_geometry",
    "pick_release_asset",
    "pick_microphone_device",
    "pick_output_device",
    "profile_values",
    "prompts_dir",
    "get_config_path",
    "get_db_path",
    "get_prompts_dir",
    "list_input_device_entries_safe",
    "list_microphone_names_safe",
    "list_output_device_entries_safe",
    "list_output_device_names_safe",
    "load_custom_action_entries",
    "resource_path",
    "runtime_root_path",
    "set_windows_app_id",
    "strip_wake_word",
    "detect_wake_word",
    "update_status_path",
    "version_tuple",
]
